# Generated by Django 4.2.10 on 2024-03-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.store')),
            ],
        ),
    ]
